#!/usr/bin/env python3
"""
disambiguation.py

Wikipedia disambiguation module for B-roll automation.

This module provides intelligent disambiguation when Wikipedia searches return
multiple potential matches. Uses Claude structured outputs to select the
contextually correct article based on transcript context, with confidence
scoring to enable auto-acceptance of high-confidence matches.

Key Features:
1. Multi-candidate Wikipedia search (top 3 results per query)
2. Disambiguation page detection via MediaWiki pageprops API
3. LLM-powered candidate selection with confidence scoring (0-10)
4. Depth-limited disambiguation resolution (max 3 attempts)
5. Caching for Wikipedia lookups (7-day TTL)

Architecture:
- CandidateInfo/DisambiguationDecision: Pydantic models for structured output
- search_wikipedia_candidates: Multi-candidate search via MediaWiki API
- is_disambiguation_page: Detect disambiguation pages using pageprops
- extract_disambiguation_links: Extract article links from disambiguation pages
- fetch_candidate_info: Get summaries and categories with caching
- disambiguate_entity: LLM-powered candidate selection
- resolve_disambiguation: Depth-limited recursive resolution
- disambiguate_search_results: Main entry point for disambiguation

Usage:
    # As a module
    from tools.disambiguation import (
        disambiguate_search_results,
        DisambiguationDecision,
        CandidateInfo
    )

    # Disambiguate search results
    decision = disambiguate_search_results(
        entity_name="Michael Jordan",
        entity_type="people",
        transcript_context="basketball player from the 1990s",
        video_topic="NBA History",
        search_results=[...],
        session=requests_session,
        client=anthropic_client,
        cache=diskcache_instance
    )

    # As a CLI
    python tools/disambiguation.py --query "Michael Jordan" --context "basketball player" --video-topic "NBA History"
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime
from pathlib import Path
from typing import List, Optional, Tuple
import tempfile

import requests
from anthropic import Anthropic
from diskcache import Cache
from pydantic import BaseModel, Field
from tenacity import retry, stop_after_attempt, wait_exponential
import wikipediaapi


# =============================================================================
# Constants
# =============================================================================

WIKIPEDIA_API = "https://en.wikipedia.org/w/api.php"
USER_AGENT = "B-Roll-Finder/1.0 (automated Wikipedia disambiguation)"


# =============================================================================
# Pydantic Models for Structured Output
# =============================================================================


class CandidateInfo(BaseModel):
    """Information about a Wikipedia candidate article.

    Contains summary and categories for LLM-based disambiguation.
    """
    title: str = Field(
        description="Wikipedia article title"
    )
    summary: str = Field(
        description="First paragraph summary from the article"
    )
    categories: List[str] = Field(
        description="Top categories for this article (max 5)"
    )


class DisambiguationDecision(BaseModel):
    """Disambiguation decision for a single entity.

    Generated by Claude using structured outputs to ensure valid JSON.
    Includes confidence score and rationale for human review.
    """
    entity_name: str = Field(
        description="Original entity name from transcript"
    )
    chosen_article: str = Field(
        description="Selected Wikipedia article title"
    )
    confidence: int = Field(
        description="Confidence score 0-10 indicating certainty of match",
        ge=0,
        le=10
    )
    rationale: str = Field(
        description="Brief explanation of why this article was chosen"
    )
    match_quality: str = Field(
        description="Match quality assessment for routing decisions",
        pattern="^(high|medium|low|none)$"
    )
    candidates_considered: List[str] = Field(
        description="All candidate titles that were compared"
    )


class DisambiguationReviewEntry(BaseModel):
    """Entry for human review of uncertain disambiguation.

    Includes all candidates considered, chosen article, confidence score,
    and context to help human reviewers understand the decision.
    """
    entity_name: str = Field(
        description="Original entity name from transcript"
    )
    entity_type: str = Field(
        description="Entity type (people, events, places, organizations, concepts)"
    )
    candidates: List[dict] = Field(
        description="All candidates with title, summary, categories"
    )
    chosen_article: str = Field(
        description="Wikipedia article selected by LLM"
    )
    confidence: int = Field(
        description="Confidence score 0-10",
        ge=0,
        le=10
    )
    rationale: str = Field(
        description="LLM explanation of why this article was chosen"
    )
    transcript_context: str = Field(
        description="Context from transcript where entity appears"
    )
    video_topic: str = Field(
        description="Video topic for disambiguation context"
    )
    match_quality: str = Field(
        description="Match quality: high/medium/low/none",
        pattern="^(high|medium|low|none)$"
    )


# =============================================================================
# Quality Tracking and Confidence Routing
# =============================================================================


def derive_match_quality(confidence: int, disambiguation_source: str = "") -> str:
    """Derive match_quality from confidence score and source.

    Per QUAL-01 through QUAL-05:
    - high: confidence >= 7 (clear disambiguation or single result)
    - medium: confidence 4-6 (successful with moderate confidence)
    - low: confidence 1-3 (uncertain but got some result)
    - none: confidence 0 (no match found)

    Args:
        confidence: Confidence score 0-10
        disambiguation_source: Source of disambiguation (for context, not used in logic)

    Returns:
        Match quality string: "high", "medium", "low", or "none"

    Example:
        >>> derive_match_quality(8)
        'high'
        >>> derive_match_quality(5)
        'medium'
        >>> derive_match_quality(2)
        'low'
        >>> derive_match_quality(0)
        'none'
    """
    if confidence >= 7:
        return "high"
    elif confidence >= 4:
        return "medium"
    elif confidence >= 1:
        return "low"
    else:
        return "none"


def apply_confidence_routing(
    decision: DisambiguationDecision,
    entity_name: str,
    entity_type: str,
    candidates: List[CandidateInfo],
    transcript_context: str,
    video_topic: str
) -> Tuple[str, Optional[DisambiguationReviewEntry]]:
    """Route entity based on disambiguation confidence.

    Returns: (action, review_entry)
    - action is one of: "download", "flag_and_download", "skip"
    - review_entry is populated only for "flag_and_download"

    Per CONTEXT.md decisions:
    - Confidence 7+: auto-accept, proceed with download -> ("download", None)
    - Confidence 4-6: flag as "needs review" but still use -> ("flag_and_download", entry)
    - Confidence 0-3: skip entity, mark as "no match" -> ("skip", None)

    Args:
        decision: DisambiguationDecision from LLM
        entity_name: Original entity name
        entity_type: Entity type (people, events, places, organizations, concepts)
        candidates: List of CandidateInfo objects considered
        transcript_context: Context from transcript
        video_topic: Video topic for disambiguation

    Returns:
        Tuple of (action, review_entry or None)

    Example:
        >>> decision = DisambiguationDecision(...)
        >>> action, entry = apply_confidence_routing(decision, "Jordan", "people", [...], "basketball", "NBA")
        >>> action
        'download'
    """
    if decision.confidence >= 7:
        # High confidence - auto-accept
        return ("download", None)

    elif decision.confidence >= 4:
        # Medium confidence - flag for review but still use
        review_entry = DisambiguationReviewEntry(
            entity_name=entity_name,
            entity_type=entity_type,
            candidates=[
                {
                    "title": c.title,
                    "summary": c.summary,
                    "categories": c.categories
                }
                for c in candidates
            ],
            chosen_article=decision.chosen_article,
            confidence=decision.confidence,
            rationale=decision.rationale,
            transcript_context=transcript_context,
            video_topic=video_topic,
            match_quality=decision.match_quality
        )
        return ("flag_and_download", review_entry)

    else:
        # Low confidence or no match - skip
        return ("skip", None)


def log_disambiguation_decision(
    entity_name: str,
    decision: DisambiguationDecision,
    action: str
) -> None:
    """Log disambiguation decision per QUAL-07.

    Logs: entity name, candidates considered, chosen article,
    confidence score, rationale, action taken.

    Args:
        entity_name: Entity being disambiguated
        decision: DisambiguationDecision from LLM
        action: Action taken (download, flag_and_download, skip)

    Example:
        >>> log_disambiguation_decision("Jordan", decision, "download")
        [Disambiguation] Jordan -> Michael Jordan (confidence: 9, action: download)
    """
    print(
        f"[Disambiguation] {entity_name} -> {decision.chosen_article or 'NO MATCH'} "
        f"(confidence: {decision.confidence}, quality: {decision.match_quality}, action: {action})",
        file=sys.stderr
    )
    if decision.candidates_considered:
        print(
            f"  Candidates: {', '.join(decision.candidates_considered)}",
            file=sys.stderr
        )
    if decision.rationale:
        print(f"  Rationale: {decision.rationale}", file=sys.stderr)


def process_disambiguation_result(
    decision: DisambiguationDecision,
    entity_name: str,
    entity_type: str,
    candidates: List[CandidateInfo],
    transcript_context: str,
    video_topic: str,
    review_entries: List[DisambiguationReviewEntry]
) -> dict:
    """Process disambiguation decision into entity metadata.

    Returns dict with:
    - wikipedia_title: Selected article or None
    - disambiguation_source: How article was selected
    - confidence: 0-10 score
    - match_quality: high/medium/low/none
    - rationale: LLM explanation
    - candidates_considered: All evaluated titles
    - action: download/flag_and_download/skip

    Also appends to review_entries if flagged for review.

    Args:
        decision: DisambiguationDecision from LLM
        entity_name: Original entity name
        entity_type: Entity type (people, events, places, organizations, concepts)
        candidates: List of CandidateInfo objects considered
        transcript_context: Context from transcript
        video_topic: Video topic for disambiguation
        review_entries: List to append review entry to (modified in place)

    Returns:
        Dict with disambiguation metadata for entity

    Example:
        >>> review_entries = []
        >>> metadata = process_disambiguation_result(
        ...     decision, "Jordan", "people", candidates,
        ...     "basketball player", "NBA", review_entries
        ... )
        >>> metadata["action"]
        'download'
    """
    # Apply confidence routing
    action, review_entry = apply_confidence_routing(
        decision, entity_name, entity_type, candidates,
        transcript_context, video_topic
    )

    # If flagged for review, add to review entries list
    if review_entry is not None:
        review_entries.append(review_entry)

    # Log decision
    log_disambiguation_decision(entity_name, decision, action)

    # Build metadata dict
    metadata = {
        "wikipedia_title": decision.chosen_article if decision.chosen_article else None,
        "disambiguation_source": "llm_disambiguation",
        "confidence": decision.confidence,
        "match_quality": decision.match_quality,
        "rationale": decision.rationale,
        "candidates_considered": decision.candidates_considered,
        "action": action
    }

    return metadata


# =============================================================================
# Review and Override File Operations
# =============================================================================


def write_review_file(
    entries: List[DisambiguationReviewEntry],
    output_path: Path
) -> None:
    """Write disambiguation review file for human oversight.

    Only includes entities with confidence 4-6 (needs review).

    Output format:
    {
        "generated": "ISO timestamp",
        "instructions": "How to override...",
        "entities": [
            {
                "entity_name": "...",
                "entity_type": "...",
                "candidates": [...],
                "chosen_article": "...",
                "confidence": N,
                "rationale": "...",
                "transcript_context": "...",
                "video_topic": "...",
                "match_quality": "..."
            }
        ]
    }

    Uses atomic write pattern (tempfile + os.replace) for safe output.
    Sorts entities by confidence (lowest first for easier review).

    Args:
        entries: List of DisambiguationReviewEntry objects
        output_path: Path to output review JSON file

    Example:
        >>> entries = [...]
        >>> write_review_file(entries, Path("output/disambiguation_review.json"))
    """
    # Sort by confidence (lowest first for easier review)
    sorted_entries = sorted(entries, key=lambda e: e.confidence)

    review_data = {
        "generated": datetime.utcnow().isoformat() + "Z",
        "instructions": (
            "Review entities below where disambiguation was uncertain (confidence 4-6). "
            "To override a choice, add an entry to disambiguation_overrides.json with format: "
            '{\"entity_name\": \"Correct_Wikipedia_Article_Title\"}'
        ),
        "entities": [entry.model_dump() for entry in sorted_entries]
    }

    # Atomic write pattern: write to temp file, then replace
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode='w',
        dir=output_path.parent,
        delete=False,
        suffix='.tmp'
    ) as tmp_file:
        json.dump(review_data, tmp_file, indent=2)
        tmp_name = tmp_file.name

    # Atomic replace
    os.replace(tmp_name, output_path)


def load_overrides(override_path: Path) -> dict:
    """Load manual disambiguation overrides.

    Override file format: {"entity_name": "Wikipedia_Article_Title"}
    Returns empty dict if file doesn't exist.

    Ignores keys starting with underscore (for comments/examples).

    Args:
        override_path: Path to overrides JSON file

    Returns:
        Dict mapping entity names to Wikipedia article titles

    Example:
        >>> overrides = load_overrides(Path("output/disambiguation_overrides.json"))
        >>> overrides.get("Jordan")
        'Michael Jordan'
    """
    if not override_path.exists():
        return {}

    with open(override_path, 'r') as f:
        data = json.load(f)

    # Filter out comment/example keys (start with underscore)
    return {k: v for k, v in data.items() if not k.startswith('_')}


def get_override(
    entity_name: str,
    overrides: dict
) -> Optional[str]:
    """Check if entity has manual override.

    Returns Wikipedia article title if override exists, None otherwise.
    Overrides take precedence over LLM disambiguation.

    Args:
        entity_name: Entity name to check
        overrides: Override dict from load_overrides()

    Returns:
        Wikipedia article title if override exists, None otherwise

    Example:
        >>> overrides = {"Jordan": "Michael Jordan"}
        >>> get_override("Jordan", overrides)
        'Michael Jordan'
        >>> get_override("Einstein", overrides)
        None
    """
    return overrides.get(entity_name)


def create_override_entry(
    entity_name: str,
    wikipedia_title: str
) -> dict:
    """Create override entry for manual correction.

    Returns dict suitable for adding to overrides file.

    Args:
        entity_name: Entity name to override
        wikipedia_title: Correct Wikipedia article title

    Returns:
        Dict with single key-value pair for override

    Example:
        >>> create_override_entry("Jordan", "Michael Jordan")
        {'Jordan': 'Michael Jordan'}
    """
    return {entity_name: wikipedia_title}


# =============================================================================
# Wikipedia API Functions
# =============================================================================


def search_wikipedia_candidates(
    session: requests.Session,
    query: str,
    limit: int = 3
) -> List[dict]:
    """Search Wikipedia and return top N candidates.

    Uses MediaWiki API with srlimit parameter to fetch multiple search results.

    Args:
        session: requests.Session for connection pooling
        query: Search query (entity name or search strategy)
        limit: Maximum number of candidates to return (default 3)

    Returns:
        List of dicts with keys: pageid, title, snippet

    Raises:
        requests.HTTPError: On API failures

    Example:
        >>> session = requests.Session()
        >>> results = search_wikipedia_candidates(session, "Michael Jordan", limit=3)
        >>> len(results) <= 3
        True
    """
    params = {
        "action": "query",
        "list": "search",
        "srsearch": query,
        "srlimit": limit,
        "srprop": "snippet",
        "format": "json",
        "formatversion": 2,
        "utf8": 1,
        "maxlag": 5,
    }

    resp = session.get(
        WIKIPEDIA_API,
        params=params,
        headers={"User-Agent": USER_AGENT},
        timeout=30
    )
    resp.raise_for_status()
    data = resp.json()

    results = data.get("query", {}).get("search", [])
    return [
        {
            "pageid": r.get("pageid"),
            "title": r.get("title"),
            "snippet": r.get("snippet", "")
        }
        for r in results
    ]


def is_disambiguation_page(
    session: requests.Session,
    title: str
) -> bool:
    """Check if page is a disambiguation page using pageprops API.

    CRITICAL: The 'disambiguation' property is an EMPTY STRING when present.
    Must check key existence ("disambiguation" in pageprops), NOT value truthiness.

    Args:
        session: requests.Session for connection pooling
        title: Wikipedia article title to check

    Returns:
        True if page is a disambiguation page, False otherwise

    Example:
        >>> session = requests.Session()
        >>> is_disambiguation_page(session, "Jordan")
        True
        >>> is_disambiguation_page(session, "Michael Jordan")
        False
    """
    params = {
        "action": "query",
        "titles": title,
        "prop": "pageprops",
        "ppprop": "disambiguation",
        "format": "json",
        "formatversion": 2,
    }

    resp = session.get(
        WIKIPEDIA_API,
        params=params,
        headers={"User-Agent": USER_AGENT},
        timeout=30
    )
    resp.raise_for_status()
    data = resp.json()

    pages = data.get("query", {}).get("pages", [])
    if not pages:
        return False

    page = pages[0]
    pageprops = page.get("pageprops", {})

    # Key insight: disambiguation prop is EMPTY STRING when present
    # Must check key existence, not value truthiness
    return "disambiguation" in pageprops


def extract_disambiguation_links(
    session: requests.Session,
    title: str,
    limit: int = 5
) -> List[str]:
    """Extract article links from a disambiguation page.

    Uses prop=links with plnamespace=0 (main namespace only) to get
    article links from a disambiguation page.

    Args:
        session: requests.Session for connection pooling
        title: Disambiguation page title
        limit: Maximum number of links to extract (default 5)

    Returns:
        List of article titles linked from the disambiguation page

    Example:
        >>> session = requests.Session()
        >>> links = extract_disambiguation_links(session, "Jordan", limit=5)
        >>> "Michael Jordan" in links
        True
    """
    params = {
        "action": "query",
        "titles": title,
        "prop": "links",
        "pllimit": limit * 2,  # Fetch extra to allow filtering
        "plnamespace": 0,  # Main namespace only (articles)
        "format": "json",
        "formatversion": 2,
    }

    resp = session.get(
        WIKIPEDIA_API,
        params=params,
        headers={"User-Agent": USER_AGENT},
        timeout=30
    )
    resp.raise_for_status()
    data = resp.json()

    pages = data.get("query", {}).get("pages", [])
    if not pages:
        return []

    links = pages[0].get("links", [])
    return [link["title"] for link in links[:limit]]


def fetch_candidate_info(
    titles: List[str],
    cache: Cache,
    cache_ttl: int = 7 * 24 * 3600
) -> List[CandidateInfo]:
    """Fetch summaries and categories for Wikipedia candidates.

    Uses Wikipedia-API library for summaries and categories.
    Caches results with 7-day TTL to reduce API load.

    Args:
        titles: List of Wikipedia article titles
        cache: DiskCache instance for persistent caching
        cache_ttl: Cache time-to-live in seconds (default 7 days)

    Returns:
        List of CandidateInfo objects with summary and categories

    Example:
        >>> cache = Cache("/tmp/wikipedia_cache")
        >>> titles = ["Michael Jordan", "Albert Einstein"]
        >>> candidates = fetch_candidate_info(titles, cache)
        >>> len(candidates) == 2
        True
    """
    wiki = wikipediaapi.Wikipedia(
        user_agent=USER_AGENT,
        language='en'
    )

    candidates = []
    for title in titles:
        # Check cache first
        cache_key = f"candidate:{title}"
        cached = cache.get(cache_key)
        if cached is not None:
            candidates.append(CandidateInfo(**cached))
            continue

        # Fetch from Wikipedia
        page = wiki.page(title)
        if not page.exists():
            continue

        info = CandidateInfo(
            title=page.title,
            summary=page.summary[:500],  # First 500 chars
            categories=list(page.categories.keys())[:5]
        )

        # Cache result
        cache.set(cache_key, info.model_dump(), expire=cache_ttl)
        candidates.append(info)

    return candidates


# =============================================================================
# LLM Disambiguation with Structured Outputs
# =============================================================================


@retry(stop=stop_after_attempt(3), wait=wait_exponential(multiplier=1, min=1, max=10))
def disambiguate_entity(
    entity_name: str,
    entity_type: str,
    transcript_context: str,
    candidates: List[CandidateInfo],
    video_topic: str,
    client: Anthropic
) -> DisambiguationDecision:
    """Use Claude to select best Wikipedia candidate.

    Uses Claude Sonnet 4.5 with structured outputs (beta) to select the
    best matching Wikipedia article from multiple candidates. Includes
    explicit confidence rubric in prompt for reliable scoring.

    Args:
        entity_name: Original entity name from transcript
        entity_type: Entity type (people, events, places, organizations, concepts)
        transcript_context: Context from transcript where entity appears
        candidates: List of CandidateInfo objects to choose from
        video_topic: Video topic/title for disambiguation hints
        client: Anthropic API client instance

    Returns:
        DisambiguationDecision with chosen article and confidence score

    Raises:
        anthropic.APIError: On API failures (retried 3x with exponential backoff)

    Example:
        >>> client = Anthropic(api_key="...")
        >>> decision = disambiguate_entity(
        ...     entity_name="Jordan",
        ...     entity_type="people",
        ...     transcript_context="basketball player from the 1990s",
        ...     candidates=[...],
        ...     video_topic="NBA History",
        ...     client=client
        ... )
        >>> decision.confidence
        9
    """
    # Format candidates for prompt
    candidate_text = "\n\n".join([
        f"Candidate {i+1}: {c.title}\n"
        f"Summary: {c.summary}\n"
        f"Categories: {', '.join(c.categories[:5])}"
        for i, c in enumerate(candidates)
    ])

    prompt = f"""Video topic: {video_topic}

Entity to disambiguate: {entity_name} (type: {entity_type})

Transcript context where entity appears:
"{transcript_context}"

Wikipedia candidates:
{candidate_text}

Select the best matching Wikipedia article for this entity.

Confidence rubric:
- 8-10: Clear match, article directly about the entity in this context
- 5-7: Likely match but some ambiguity remains
- 2-4: Uncertain, multiple candidates could fit
- 0-1: No good match found

Match quality guidelines:
- high: Single obvious match or confident disambiguation (confidence >= 7)
- medium: Successful disambiguation with moderate confidence (4-6)
- low: All strategies uncertain but got some result (confidence 1-3)
- none: No match found (confidence 0)

Consider:
1. Does the candidate summary match the transcript context?
2. Is the entity type consistent (person mentioned in transcript should match person article)?
3. Does the video topic provide disambiguation hints?"""

    response = client.beta.messages.parse(
        model="claude-sonnet-4-5-20250929",
        max_tokens=1024,
        betas=["structured-outputs-2025-11-13"],
        messages=[{"role": "user", "content": prompt}],
        output_format=DisambiguationDecision,
    )

    return response.parsed_output


# =============================================================================
# Depth-Limited Disambiguation Resolution
# =============================================================================


def resolve_disambiguation(
    session: requests.Session,
    entity_name: str,
    entity_type: str,
    initial_title: str,
    transcript_context: str,
    video_topic: str,
    client: Anthropic,
    cache: Cache,
    max_depth: int = 3,
    current_depth: int = 0
) -> Optional[DisambiguationDecision]:
    """Resolve disambiguation page with depth limit.

    Recursively resolves disambiguation pages by extracting linked articles
    and running LLM disambiguation on them. Enforces max_depth to prevent
    infinite loops (CONTEXT.md: max 3 attempts).

    Args:
        session: requests.Session for Wikipedia API calls
        entity_name: Original entity name from transcript
        entity_type: Entity type (people, events, places, organizations, concepts)
        initial_title: Wikipedia article title to check/resolve
        transcript_context: Context from transcript where entity appears
        video_topic: Video topic/title for disambiguation hints
        client: Anthropic API client instance
        cache: DiskCache instance for caching
        max_depth: Maximum disambiguation attempts (default 3 per CONTEXT.md)
        current_depth: Current recursion depth (internal use)

    Returns:
        DisambiguationDecision or None if all attempts failed

    Example:
        >>> decision = resolve_disambiguation(
        ...     session=session,
        ...     entity_name="Jordan",
        ...     entity_type="people",
        ...     initial_title="Jordan",
        ...     transcript_context="basketball player",
        ...     video_topic="NBA History",
        ...     client=client,
        ...     cache=cache
        ... )
        >>> decision.chosen_article
        'Michael Jordan'
    """
    if current_depth >= max_depth:
        print(f"Max disambiguation depth reached for {entity_name}", file=sys.stderr)
        return None

    # Check if this is a disambiguation page
    if not is_disambiguation_page(session, initial_title):
        # Not a disambiguation page - return as valid result
        return DisambiguationDecision(
            entity_name=entity_name,
            chosen_article=initial_title,
            confidence=7,  # Single result, moderate confidence
            rationale="Direct match, not a disambiguation page",
            match_quality="medium",
            candidates_considered=[initial_title]
        )

    # Extract links from disambiguation page
    linked_titles = extract_disambiguation_links(session, initial_title, limit=5)

    if not linked_titles:
        print(f"No links found on disambiguation page: {initial_title}", file=sys.stderr)
        return None

    # Filter out nested disambiguation pages
    valid_titles = []
    for title in linked_titles:
        if is_disambiguation_page(session, title):
            # Skip nested disambiguation pages
            print(f"Skipping nested disambiguation page: {title}", file=sys.stderr)
            continue
        valid_titles.append(title)

    if not valid_titles:
        print(f"All linked pages are disambiguation pages for: {entity_name}", file=sys.stderr)
        return None

    # Fetch summaries for valid candidates
    candidates = fetch_candidate_info(valid_titles, cache)

    if not candidates:
        print(f"No valid candidates found for: {entity_name}", file=sys.stderr)
        return None

    # Use LLM to select best candidate
    decision = disambiguate_entity(
        entity_name=entity_name,
        entity_type=entity_type,
        transcript_context=transcript_context,
        candidates=candidates,
        video_topic=video_topic,
        client=client
    )

    # Recursively check if chosen article is also a disambiguation page
    if is_disambiguation_page(session, decision.chosen_article):
        return resolve_disambiguation(
            session, entity_name, entity_type, decision.chosen_article,
            transcript_context, video_topic, client, cache,
            max_depth, current_depth + 1
        )

    return decision


# =============================================================================
# Main Disambiguation Entry Point
# =============================================================================


def disambiguate_search_results(
    entity_name: str,
    entity_type: str,
    transcript_context: str,
    video_topic: str,
    search_results: List[dict],
    session: requests.Session,
    client: Anthropic,
    cache: Cache
) -> DisambiguationDecision:
    """Main entry point for disambiguation.

    Handles three scenarios:
    1. Single result: check if disambiguation page, return moderate confidence
    2. Multiple results: run full LLM disambiguation
    3. Disambiguation page: resolve with depth limit

    Args:
        entity_name: Original entity name from transcript
        entity_type: Entity type (people, events, places, organizations, concepts)
        transcript_context: Context from transcript where entity appears
        video_topic: Video topic/title for disambiguation hints
        search_results: List of search results from search_wikipedia_candidates
        session: requests.Session for Wikipedia API calls
        client: Anthropic API client instance
        cache: DiskCache instance for caching

    Returns:
        DisambiguationDecision with chosen article and confidence

    Example:
        >>> decision = disambiguate_search_results(
        ...     entity_name="Michael Jordan",
        ...     entity_type="people",
        ...     transcript_context="basketball player",
        ...     video_topic="NBA History",
        ...     search_results=[...],
        ...     session=session,
        ...     client=client,
        ...     cache=cache
        ... )
    """
    if not search_results:
        # No results found
        return DisambiguationDecision(
            entity_name=entity_name,
            chosen_article="",
            confidence=0,
            rationale="No Wikipedia search results found",
            match_quality="none",
            candidates_considered=[]
        )

    if len(search_results) == 1:
        # Single result - check if disambiguation page
        title = search_results[0]["title"]
        if is_disambiguation_page(session, title):
            # Resolve disambiguation page
            decision = resolve_disambiguation(
                session, entity_name, entity_type, title,
                transcript_context, video_topic, client, cache
            )
            if decision:
                return decision
            else:
                # Disambiguation resolution failed
                return DisambiguationDecision(
                    entity_name=entity_name,
                    chosen_article="",
                    confidence=0,
                    rationale="Disambiguation page resolution failed",
                    match_quality="none",
                    candidates_considered=[title]
                )
        else:
            # Single non-disambiguation result
            return DisambiguationDecision(
                entity_name=entity_name,
                chosen_article=title,
                confidence=7,  # Moderate confidence for single result
                rationale="Single search result, not a disambiguation page",
                match_quality="medium",
                candidates_considered=[title]
            )

    # Multiple candidates - run disambiguation
    titles = [r["title"] for r in search_results]
    candidates = fetch_candidate_info(titles, cache)

    if not candidates:
        return DisambiguationDecision(
            entity_name=entity_name,
            chosen_article="",
            confidence=0,
            rationale="No valid candidates after fetching summaries",
            match_quality="none",
            candidates_considered=titles
        )

    decision = disambiguate_entity(
        entity_name=entity_name,
        entity_type=entity_type,
        transcript_context=transcript_context,
        candidates=candidates,
        video_topic=video_topic,
        client=client
    )

    return decision


# =============================================================================
# CLI Interface
# =============================================================================


def main(argv: List[str] = None) -> int:
    """CLI entry point for disambiguation testing.

    Usage:
        python tools/disambiguation.py --query "Michael Jordan" --context "basketball player" --video-topic "NBA History"

    Returns:
        0 on success, 1 on error, 2 on missing API key
    """
    parser = argparse.ArgumentParser(
        description="Test Wikipedia disambiguation for an entity"
    )
    parser.add_argument(
        "--query",
        required=True,
        help="Entity name to disambiguate"
    )
    parser.add_argument(
        "--context",
        default="",
        help="Transcript context where entity appears"
    )
    parser.add_argument(
        "--video-topic",
        default="Unknown video",
        help="Video topic for disambiguation"
    )
    parser.add_argument(
        "--cache-dir",
        default="/tmp/wikipedia_cache",
        help="Cache directory (default: /tmp/wikipedia_cache)"
    )
    parser.add_argument(
        "--entity-type",
        default="concepts",
        help="Entity type (people, events, places, organizations, concepts)"
    )

    args = parser.parse_args(argv)

    # Create session and cache
    session = requests.Session()
    cache = Cache(args.cache_dir)

    # Search for candidates
    print(f"Searching Wikipedia for: {args.query}", file=sys.stderr)
    try:
        search_results = search_wikipedia_candidates(session, args.query, limit=3)
    except Exception as e:
        print(f"Error: Wikipedia search failed: {e}", file=sys.stderr)
        return 1

    if not search_results:
        print("No search results found", file=sys.stderr)
        return 0

    print(f"Found {len(search_results)} candidates:", file=sys.stderr)
    for i, result in enumerate(search_results, 1):
        print(f"  {i}. {result['title']}", file=sys.stderr)

    # Check if API key is available for LLM disambiguation
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("\nANTHROPIC_API_KEY not set - skipping LLM disambiguation", file=sys.stderr)
        print("Set API key to run full disambiguation with confidence scoring", file=sys.stderr)
        return 2

    # Run disambiguation
    client = Anthropic(api_key=api_key)
    try:
        decision = disambiguate_search_results(
            entity_name=args.query,
            entity_type=args.entity_type,
            transcript_context=args.context,
            video_topic=args.video_topic,
            search_results=search_results,
            session=session,
            client=client,
            cache=cache
        )
    except Exception as e:
        print(f"Error: Disambiguation failed: {e}", file=sys.stderr)
        return 1

    # Print decision
    print("\n=== Disambiguation Decision ===", file=sys.stderr)
    print(json.dumps(decision.model_dump(), indent=2))

    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        print("\nInterrupted.", file=sys.stderr)
        sys.exit(130)
