#!/usr/bin/env python3
"""
generate_search_strategies.py

LLM-powered search strategy generator for B-roll automation.

This module provides:
1. SearchStrategy Pydantic models - Structured LLM output schemas
2. WikipediaValidator - Title validation with persistent caching
3. generate_search_strategies - Main entry point for strategy generation
4. CLI interface - Process enriched_entities.json to add search strategies

The LLM generates 2-3 Wikipedia search queries per entity instead of using
naive entity names. This improves match success rate from ~60% to 85-90%.

Usage:
    # As a module
    from tools.generate_search_strategies import (
        generate_search_strategies,
        WikipediaValidator,
        SearchStrategy
    )

    # Generate strategies
    enriched = generate_search_strategies(
        enriched_map,
        video_context="AI and Machine Learning",
        batch_size=7
    )

    # As a CLI
    python tools/generate_search_strategies.py --map enriched_entities.json --video-context "AI Tutorial"
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
from typing import Dict, List, Optional

from anthropic import Anthropic
from diskcache import Cache
from pydantic import BaseModel, Field
from tenacity import retry, stop_after_attempt, wait_exponential
import wikipediaapi


# =============================================================================
# Pydantic Schemas for Structured Output
# =============================================================================


class SearchStrategy(BaseModel):
    """Search strategy for a single entity.

    Generated by Claude using structured outputs to ensure valid JSON.
    """
    entity_name: str = Field(
        description="Original entity name from transcript"
    )
    entity_type: str = Field(
        description="Entity type (people, events, organizations, concepts, places)"
    )
    best_title: str = Field(
        description="Most likely Wikipedia article title (exact match preferred)"
    )
    queries: List[str] = Field(
        description="2-3 search queries ordered by confidence (most likely first). "
                    "People get 3 queries, others get 2.",
        min_length=2,
        max_length=3
    )
    confidence: int = Field(
        description="Confidence score 1-10 indicating certainty of match",
        ge=1,
        le=10
    )


class BatchSearchStrategies(BaseModel):
    """Batch of search strategies for multiple entities.

    Wrapper for processing 5-10 entities per LLM call.
    """
    strategies: List[SearchStrategy]


# =============================================================================
# Wikipedia Title Validation with Caching
# =============================================================================


class WikipediaValidator:
    """Validates Wikipedia article titles with persistent caching.

    Uses Wikipedia-API to check if titles exist and get canonical forms.
    Results are cached with configurable TTL (default 7 days) to reduce
    redundant API calls.

    Attributes:
        cache: DiskCache instance for persistent storage
        cache_ttl: Time-to-live in seconds for cached results
        wiki: Wikipedia API client
    """

    def __init__(
        self,
        cache_dir: str = "/tmp/wikipedia_cache",
        cache_ttl_days: int = 7
    ):
        """Initialize validator with cache configuration.

        Args:
            cache_dir: Directory for persistent cache storage
            cache_ttl_days: Number of days to cache validation results
        """
        self.cache = Cache(cache_dir)
        self.cache_ttl = cache_ttl_days * 24 * 3600  # Convert to seconds
        self.wiki = wikipediaapi.Wikipedia(
            user_agent='B-Roll-Finder/1.0 (automated Wikipedia lookup)',
            language='en'
        )

    def validate(self, title: str) -> dict:
        """Validate Wikipedia title exists, return canonical form.

        Checks cache first, then queries Wikipedia API if needed.
        Handles redirects and returns canonical title/URL.

        Args:
            title: Wikipedia article title to validate

        Returns:
            Dict with keys:
                - exists: bool - Whether article exists
                - canonical_title: str or None - Canonical title (handles redirects)
                - canonical_url: str or None - Full Wikipedia URL

        Examples:
            >>> validator = WikipediaValidator()
            >>> result = validator.validate('Albert Einstein')
            >>> result['exists']
            True
            >>> result['canonical_title']
            'Albert Einstein'
        """
        # Check cache first
        cache_key = f"wiki:{title}"
        cached = self.cache.get(cache_key)
        if cached is not None:
            return cached

        # Fetch from Wikipedia API
        page = self.wiki.page(title)
        result = {
            "exists": page.exists(),
            "canonical_title": page.title if page.exists() else None,
            "canonical_url": page.canonicalurl if page.exists() else None
        }

        # Cache result with TTL
        self.cache.set(cache_key, result, expire=self.cache_ttl)

        return result


# =============================================================================
# LLM Strategy Generation with Batch Processing
# =============================================================================


def _format_entities_for_prompt(entities: List[dict]) -> str:
    """Format entity batch for LLM prompt.

    Args:
        entities: List of entity dicts with name, entity_type, context

    Returns:
        Formatted string for prompt
    """
    lines = []
    for i, entity in enumerate(entities, 1):
        lines.append(f"{i}. {entity['name']}")
        lines.append(f"   Type: {entity['entity_type']}")
        lines.append(f"   Context: {entity.get('context', 'No context')[:150]}")
        lines.append("")

    return "\n".join(lines)


@retry(stop=stop_after_attempt(3), wait=wait_exponential(multiplier=1, min=1, max=10))
def generate_batch_strategies(
    entities: List[dict],
    video_context: str,
    client: Anthropic
) -> List[SearchStrategy]:
    """Generate search strategies for a batch of entities using Claude.

    Uses Claude Sonnet 4.5 with structured outputs (beta) to generate
    2-3 Wikipedia search queries per entity. Guaranteed valid JSON output.

    Args:
        entities: List of entity dicts with keys:
            - name: str
            - entity_type: str (people, events, organizations, concepts, places)
            - context: str (transcript context from Phase 1)
        video_context: Video topic/title for disambiguation
        client: Anthropic API client instance

    Returns:
        List of SearchStrategy objects (one per entity)

    Raises:
        anthropic.APIError: On API failures (retried 3x with exponential backoff)
    """
    prompt = f"""Video topic: {video_context}

Generate Wikipedia search strategies for these entities:

{_format_entities_for_prompt(entities)}

For each entity, provide:
1. best_title: The most likely exact Wikipedia article title
2. queries: 2-3 alternative search queries ordered by confidence
   - People get 3 queries (full name, common variation, role-based)
   - Other types get 2 queries
3. confidence: Score 1-10 based on certainty

Guidelines:
- Order queries by likelihood of success (most confident first)
- Include disambiguation hints (profession, era, location) ONLY when entity name is ambiguous
- Use video topic to disambiguate (e.g., "Jordan" in basketball video = Michael Jordan, not country)
- Prefer exact Wikipedia article titles when you're confident

Examples:
- "Elon Musk" (people) → best_title: "Elon Musk", queries: ["Elon Musk", "Musk entrepreneur", "Elon Musk SpaceX"]
- "World War II" (events) → best_title: "World War II", queries: ["World War II", "Second World War"]
- "Paris" (places, travel video) → best_title: "Paris", queries: ["Paris", "Paris France"]
"""

    response = client.beta.messages.parse(
        model="claude-sonnet-4-5-20250929",
        max_tokens=2048,
        betas=["structured-outputs-2025-11-13"],
        messages=[{"role": "user", "content": prompt}],
        output_format=BatchSearchStrategies,
    )

    return response.parsed_output.strategies


def generate_search_strategies(
    enriched_map: dict,
    video_context: str,
    batch_size: int = 7
) -> dict:
    """Generate search strategies for all entities in enriched_map.

    Main entry point for strategy generation. Processes entities in batches
    to reduce API calls. Handles failures gracefully with fallback to
    individual processing.

    Args:
        enriched_map: Dict with structure:
            {
                "entities": {
                    "entity_name": {
                        "entity_type": str,
                        "context": str,
                        ...
                    }
                },
                "source_srt": str
            }
        video_context: Video topic/title for disambiguation
        batch_size: Number of entities per LLM call (default 7, range 5-10)

    Returns:
        Updated enriched_map with search_strategies field added to each entity:
        {
            "best_title": str,
            "queries": List[str],
            "confidence": int,
            "status": "generated" or "failed_generation"
        }

    Raises:
        ValueError: If ANTHROPIC_API_KEY not set
    """
    # Load API key
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        raise ValueError(
            "ANTHROPIC_API_KEY environment variable not set. "
            "Get your API key from: https://console.anthropic.com/settings/keys"
        )

    client = Anthropic(api_key=api_key)

    # Prepare entity list for processing
    entities = enriched_map.get("entities", {})
    entity_list = [
        {
            "name": name,
            "entity_type": data.get("entity_type", "concepts"),
            "context": data.get("context", "")
        }
        for name, data in entities.items()
    ]

    if not entity_list:
        print("Warning: No entities to process", file=sys.stderr)
        return enriched_map

    # Process in batches
    total_generated = 0
    total_failed = 0

    for i in range(0, len(entity_list), batch_size):
        batch = entity_list[i:i+batch_size]
        batch_num = i // batch_size + 1
        total_batches = (len(entity_list) + batch_size - 1) // batch_size

        print(f"Processing batch {batch_num}/{total_batches} ({len(batch)} entities)...", file=sys.stderr)

        try:
            # Try batch processing
            strategies = generate_batch_strategies(batch, video_context, client)

            # Merge strategies into entities
            for entity, strategy in zip(batch, strategies):
                entity_name = entity["name"]
                entities[entity_name]["search_strategies"] = {
                    "best_title": strategy.best_title,
                    "queries": strategy.queries,
                    "confidence": strategy.confidence,
                    "status": "generated"
                }
                total_generated += 1

        except Exception as batch_error:
            # Batch failed after retries: fallback to individual processing
            print(f"Batch {batch_num} failed, processing individually: {batch_error}", file=sys.stderr)

            for entity in batch:
                entity_name = entity["name"]
                try:
                    # Retry as single-entity batch
                    single_batch = [entity]
                    strategies = generate_batch_strategies(single_batch, video_context, client)

                    entities[entity_name]["search_strategies"] = {
                        "best_title": strategies[0].best_title,
                        "queries": strategies[0].queries,
                        "confidence": strategies[0].confidence,
                        "status": "generated"
                    }
                    total_generated += 1

                except Exception as e:
                    # Mark as failed, use entity name as fallback
                    print(f"Failed to generate strategy for '{entity_name}': {e}", file=sys.stderr)
                    entities[entity_name]["search_strategies"] = {
                        "best_title": entity_name,
                        "queries": [entity_name],
                        "confidence": 1,
                        "status": "failed_generation"
                    }
                    total_failed += 1

    print(f"Strategy generation complete: {total_generated} generated, {total_failed} failed", file=sys.stderr)

    return enriched_map


# =============================================================================
# Wikipedia Validation
# =============================================================================


def validate_strategies(
    enriched_map: dict,
    validator: WikipediaValidator
) -> dict:
    """Validate all search strategies against Wikipedia API.

    Checks if best_title and all queries actually exist on Wikipedia.
    Filters out invalid queries and records validation results.

    Args:
        enriched_map: Dict with entities containing search_strategies
        validator: WikipediaValidator instance with caching

    Returns:
        Updated enriched_map with validation_results added to search_strategies:
        {
            "best_title_valid": bool,
            "best_title_canonical": str or None,
            "validated_queries": [
                {"query": str, "valid": bool, "canonical": str or None},
                ...
            ]
        }

        Invalid queries are filtered out, keeping only validated ones.
    """
    entities = enriched_map.get("entities", {})

    total_entities = 0
    cache_hits = 0

    for entity_name, entity_data in entities.items():
        search_strategies = entity_data.get("search_strategies")
        if not search_strategies:
            continue

        total_entities += 1

        # Validate best_title
        best_title = search_strategies.get("best_title")
        if best_title:
            # Check if this is a cache hit
            cache_key = f"wiki:{best_title}"
            is_cached = validator.cache.get(cache_key) is not None
            if is_cached:
                cache_hits += 1

            result = validator.validate(best_title)
            search_strategies["best_title_valid"] = result["exists"]
            search_strategies["best_title_canonical"] = result["canonical_title"]

        # Validate each query
        queries = search_strategies.get("queries", [])
        validated_queries = []
        valid_queries_list = []

        for query in queries:
            # Check cache
            cache_key = f"wiki:{query}"
            is_cached = validator.cache.get(cache_key) is not None
            if is_cached:
                cache_hits += 1

            result = validator.validate(query)
            validated_queries.append({
                "query": query,
                "valid": result["exists"],
                "canonical": result["canonical_title"]
            })

            # Keep only valid queries in the list
            if result["exists"]:
                valid_queries_list.append(query)

        search_strategies["validated_queries"] = validated_queries

        # Update queries list to contain only valid queries
        # If no valid queries, keep original entity name as fallback
        if valid_queries_list:
            search_strategies["queries"] = valid_queries_list
        else:
            # Fallback: use entity name
            search_strategies["queries"] = [entity_name]
            search_strategies["status"] = "fallback"

    print(f"Validation complete: {total_entities} entities validated, {cache_hits} cache hits", file=sys.stderr)

    return enriched_map


# =============================================================================
# CLI Interface
# =============================================================================


def main(argv: List[str] = None) -> int:
    """CLI entry point for search strategy generation.

    Usage:
        python tools/generate_search_strategies.py --map enriched_entities.json --video-context "AI Tutorial"

    Returns:
        0 on success, 1 on general error, 2 on missing file
    """
    parser = argparse.ArgumentParser(
        description="Generate Wikipedia search strategies for entities using Claude"
    )
    parser.add_argument(
        "--map",
        required=True,
        help="Path to enriched_entities.json (from enrich_entities.py)"
    )
    parser.add_argument(
        "--out",
        help="Output path (default: strategies_entities.json in same dir as --map)"
    )
    parser.add_argument(
        "--video-context",
        help="Video topic/title for disambiguation (default: extracted from source_srt filename)"
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=7,
        help="Number of entities per LLM call (default: 7, range: 5-10)"
    )
    parser.add_argument(
        "--cache-dir",
        default="/tmp/wikipedia_cache",
        help="Wikipedia validation cache directory (default: /tmp/wikipedia_cache)"
    )

    args = parser.parse_args(argv)

    # Validate batch size
    if not (5 <= args.batch_size <= 10):
        print("Warning: batch-size outside recommended range (5-10), continuing anyway", file=sys.stderr)

    # Validate map file exists
    if not os.path.exists(args.map):
        print(f"Error: enriched_entities file not found: {args.map}", file=sys.stderr)
        return 2

    # Load enriched_entities
    try:
        with open(args.map, "r", encoding="utf-8") as f:
            enriched_map = json.load(f)
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON in {args.map}: {e}", file=sys.stderr)
        return 1
    except Exception as e:
        print(f"Error: Failed to read {args.map}: {e}", file=sys.stderr)
        return 1

    # Extract video context
    if args.video_context:
        video_context = args.video_context
    else:
        # Extract from source_srt filename
        source_srt = enriched_map.get("source_srt", "")
        if source_srt:
            # Remove extension and path
            video_context = os.path.splitext(os.path.basename(source_srt))[0]
            video_context = video_context.replace("_", " ").replace("-", " ")
        else:
            video_context = "Unknown video"
        print(f"Using video context: {video_context}", file=sys.stderr)

    # Determine output path
    if args.out:
        out_path = args.out
    else:
        map_dir = os.path.dirname(os.path.abspath(args.map))
        out_path = os.path.join(map_dir, "strategies_entities.json")

    # Check for API key
    if not os.environ.get("ANTHROPIC_API_KEY"):
        print("Error: ANTHROPIC_API_KEY environment variable not set", file=sys.stderr)
        print("Get your API key from: https://console.anthropic.com/settings/keys", file=sys.stderr)
        return 1

    # Handle empty entities
    entities = enriched_map.get("entities", {})
    if not entities:
        print("Warning: No entities found in enriched_map", file=sys.stderr)
        # Write output with no changes
        result = enriched_map
    else:
        # Generate search strategies
        try:
            result = generate_search_strategies(
                enriched_map,
                video_context,
                batch_size=args.batch_size
            )
        except Exception as e:
            print(f"Error: Failed to generate strategies: {e}", file=sys.stderr)
            return 1

        # Validate strategies
        try:
            validator = WikipediaValidator(cache_dir=args.cache_dir)
            result = validate_strategies(result, validator)
        except Exception as e:
            print(f"Error: Failed to validate strategies: {e}", file=sys.stderr)
            return 1

    # Write output atomically (temp file + rename)
    out_dir = os.path.dirname(os.path.abspath(out_path))
    os.makedirs(out_dir, exist_ok=True)

    try:
        # Write to temp file first
        fd, temp_path = tempfile.mkstemp(suffix=".json", dir=out_dir)
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as f:
                json.dump(result, f, ensure_ascii=False, indent=2)
            # Atomic rename
            os.replace(temp_path, out_path)
        except Exception:
            # Clean up temp file on error
            if os.path.exists(temp_path):
                os.unlink(temp_path)
            raise
    except Exception as e:
        print(f"Error: Failed to write {out_path}: {e}", file=sys.stderr)
        return 1

    # Success summary
    entity_count = len(result.get("entities", {}))
    generated_count = sum(
        1 for e in result.get("entities", {}).values()
        if e.get("search_strategies", {}).get("status") == "generated"
    )
    print(f"\nProcessed {entity_count} entities: {generated_count} with valid strategies")
    print(f"Output: {os.path.abspath(out_path)}")

    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        print("\nInterrupted.", file=sys.stderr)
        sys.exit(130)
