"""
Disambiguation models for B-Roll Finder.

These models are used for LLM-powered Wikipedia disambiguation.
"""
from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class CandidateInfo(BaseModel):
    """Information about a Wikipedia candidate article.

    Contains summary and categories for LLM-based disambiguation.
    """

    title: str = Field(description="Wikipedia article title")
    summary: str = Field(description="First paragraph summary from the article")
    categories: List[str] = Field(
        default_factory=list, description="Top categories for this article (max 5)"
    )


class DisambiguationDecision(BaseModel):
    """Disambiguation decision for a single entity.

    Generated by Claude using structured outputs to ensure valid JSON.
    Includes confidence score and rationale for human review.
    """

    entity_name: str = Field(description="Original entity name from transcript")
    chosen_article: str = Field(description="Selected Wikipedia article title")
    confidence: int = Field(
        description="Confidence score 0-10 indicating certainty of match",
        ge=0,
        le=10,
    )
    rationale: str = Field(
        description="Brief explanation of why this article was chosen"
    )
    match_quality: str = Field(
        description="Match quality assessment for routing decisions",
        pattern="^(high|medium|low|none)$",
    )
    candidates_considered: List[str] = Field(
        default_factory=list, description="All candidate titles that were compared"
    )


class DisambiguationReviewEntry(BaseModel):
    """Entry for human review of uncertain disambiguation.

    Includes all candidates considered, chosen article, confidence score,
    and context to help human reviewers understand the decision.
    """

    entity_name: str = Field(description="Original entity name from transcript")
    entity_type: str = Field(
        description="Entity type (people, events, places, organizations, concepts)"
    )
    candidates: List[dict] = Field(
        description="All candidates with title, summary, categories"
    )
    chosen_article: str = Field(description="Wikipedia article selected by LLM")
    confidence: int = Field(description="Confidence score 0-10", ge=0, le=10)
    rationale: str = Field(
        description="LLM explanation of why this article was chosen"
    )
    transcript_context: str = Field(
        description="Context from transcript where entity appears"
    )
    video_topic: str = Field(description="Video topic for disambiguation context")
    match_quality: str = Field(
        description="Match quality: high/medium/low/none",
        pattern="^(high|medium|low|none)$",
    )


class DisambiguationRequest(BaseModel):
    """API request for disambiguation.

    Used by the API to request disambiguation of a single entity.
    """

    entity_name: str = Field(description="Entity name to disambiguate")
    entity_type: str = Field(
        default="concepts",
        description="Entity type (people, events, places, organizations, concepts)",
    )
    transcript_context: str = Field(
        default="", description="Context from transcript where entity appears"
    )
    video_topic: str = Field(
        default="Unknown video", description="Video topic for disambiguation"
    )
    search_limit: int = Field(
        default=3, ge=1, le=10, description="Maximum number of candidates to consider"
    )


class DisambiguationResponse(BaseModel):
    """API response for disambiguation.

    Contains the disambiguation decision and additional metadata.
    """

    decision: DisambiguationDecision = Field(
        description="The disambiguation decision"
    )
    action: str = Field(
        description="Recommended action (download, flag_and_download, skip)"
    )
    candidates: List[CandidateInfo] = Field(
        default_factory=list, description="All candidates that were considered"
    )
